services:
  - type: web
    name: webhook-transcricao-karol
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: NOTION_TOKEN
        sync: false
      - key: NOTION_DATABASE_ID
        sync: false
      - key: ZAPI_INSTANCE
        sync: false
      - key: ZAPI_TOKEN
        sync: false
      - key: ZAPI_CLIENT_TOKEN
        sync: false
      - key: ADMIN_PHONES
        sync: false
      - key: TZ
        value: America/Sao_Paulo 